# Sprint7 機械学習スクラッチ クラスタリング

## 大上さんとペアプロ

In [187]:
# 最初に使用予定のデータやライブラリーを宣言しておく
import os # ファイルの読み込み先のpath指定する時に必要

import numpy as np # numpyのライブラリー読み込み
from numpy import linalg as LA # ユークリッド距離を算出するメソッド
from numpy.random import *
import pandas as pd # pandasのライブラリー読み込み

import matplotlib.pyplot as plt # グラフ描写のライブラリー
import matplotlib.patches as mpatches # 可視化
import seaborn as sns # グラフ描写のライブラリー
from matplotlib.colors import ListedColormap # マップ

from sklearn.datasets import load_iris # アイリスデータ

from sklearn.model_selection import train_test_split # データ分割

from sklearn.preprocessing import StandardScaler # 標準化
from sklearn.neighbors import KNeighborsClassifier # 最近傍法

from sklearn.metrics import accuracy_score # 正解率
from sklearn.metrics import precision_score # 適合率
from sklearn.metrics import recall_score # 再現率
from sklearn.metrics import f1_score # F値
from sklearn.metrics import confusion_matrix # 混合行列

from sklearn import linear_model
from sklearn.linear_model import LogisticRegression # ロジスティック回帰
from sklearn.svm import SVC #SVC 
from sklearn.model_selection import cross_val_score # 決定木
from sklearn.tree import DecisionTreeClassifier # 決定木
from sklearn.ensemble import RandomForestClassifier # ランダムフォレスト1
from sklearn.datasets import make_classification # ランダムフォレスト2

from sklearn.linear_model import LinearRegression # 線形回帰モデル

In [154]:
# データの取得
from sklearn.datasets import make_blobs
# yは回答で、今回は使用しないので、_で埋めてる
X, _ = make_blobs(n_samples=100,
                  n_features=2, centers=4,
                  cluster_std=0.5,
                  shuffle=True,
                  random_state=0)
# 全データ点を表にする
# データを操作しやすいように pd に変換
X = pd.DataFrame(X,columns=['X', 'Y'])
X.head()

X         Y
0  0.720868  3.713471
1 -1.894684  7.968985
2  1.356789  4.364625
3  1.053744  4.492869
4  1.591415  4.904977

### 【問題1】中心点の初期値を決める（クラスタをあげる）

In [155]:
# データ群（今回は１００）からデータの番地を３つランダムに抽出
def get_cluster(c):
    cluster = randint(0,100,c)       #  0〜99 の整数をc個生成
    return cluster
c = 3
cluster = get_cluster(c)
print(cluster)

[20 61  7]


In [157]:
# myu 列の作成
myu = randint(0, c, 100)       #  0〜c の整数を100個生成
myu = pd.DataFrame(myu, columns=['myu'])       # aをpandasデータに変更し、列名をmyuに
myu.head()

# 全データ点座標に対して、適当なクラスタを割り当てたいので、全データ点とmyuを結合
X_myu = pd.concat([X, myu], axis=1)
X_myu.head()

# X_myu をnumpyに変更
X_myu_np = X_myu.values

# print(type(i))
# print(type(X))
# print(i.shape)
# print(X.shape)
# i.reshape(50,2)
# print(i.shape)
# np.hstack(X, i, axis=1)
# print(X)
# print(i)
# X1 = np.insert(X, 2, a,axis=1) # 2は行数指定をする
# print(X1)

In [171]:
X_myu.head()

X         Y  myu
0  0.720868  3.713471    2
1 -1.894684  7.968985    2
2  1.356789  4.364625    1
3  1.053744  4.492869    1
4  1.591415  4.904977    2

In [159]:
# myu_k の作成（myu_kは重心・クラスタの座標）
n = 0
myu_k = np.zeros(6).reshape(3,2)

# print(myu_k)
# クラスタの座標を取得する
for c in range (len(cluster)):
    myu_k[c, 0] = X_myu_np[cluster[c], 0]
    myu_k[c, 1] = X_myu_np[cluster[c], 1]

print(myu_k)

[[ 2.11114739  3.57660449]
 [ 1.51989121  1.42488952]
 [-0.77354537  7.87923564]]


In [134]:
# やろうとしたけど中止

# k番目の中心点（myu_k 番目の 入力データ）
# myu_k = X1[33]
# myu_k = X1.iloc[1]
# print(myu_k)

# print(type(X1[i[b]]))
# print(X1[i[b]].shape)
# print(X1[i[b]])
# print(k)
# myu_k = np.empty((0,5), int)
# for b in range (k):
#     print(i[b])
#     myu_k = np.hstack(X1[i[b]])
#     myu_k.insert(myu_k, X1[i[b]], axis=0)
#     myu_k = np.insert(myu_k, X1[i[b]], axis=0)
#     np.insert(myu_k, b, X1[i[b]], axis=0)
#     myu_k = np.append(myu_k, X1[i[b]], axis=0)
#     np.insert(myu_k, b, X1[i[b]], axis=0)
# pass

# myu_k.reshape(3.3)
# print(myu_k)

## 【問題2】SSEを求める関数の作成

In [135]:
X_k = np.zeros(len(X)*(k + 1)).reshape(len(X),k + 1)
# print(X_k)
# print(len(X))
k = 0
n = 0
# for k in range (len(myu_k) - 1):
for n in range (len(X) - 1):
#         print(k)
#         print(len(myu_k) - 1)
#         print(myu_k[k, 0])
#         print(myu_k[k+1, 0])
        
#         print(X_k[n, 1])
#         print(n)
#         print(len(X) - 1)
#         print(X_k[n, 1])

    X_k[n, 0] = n
    X_k[n, 1] = X[n, 0] - myu_k[0, 0]
    X_k[n, 2] = X[n, 0] - myu_k[1, 0] 
    X_k[n, 3] = X[n, 0] - myu_k[2, 0]
    pass
# print(X_k)
# ２連続で実施しようとするとこけるので、run all cells を実施する

In [179]:
def get_sse(X_myu_np,myu_k):
    for N in range (len(X_myu_np)):
#         print(N)
        for K in range (len(myu_k)):
#             print(K)
            if X_myu_np[N,2] == K:
                rnk = 1
            else:
                rnk = 0
            rmk = 0.5
#             print(X_myu_np[N,0])
#             print(X_myu_np[N,1])
#             print(myu_k[K,0])
#             print(myu_k[K,1])

            distans = abs(X_myu_np[N,0] - myu_k[K,0]) + abs(X_myu_np[N,1] - myu_k[K,1])
            sse = rmk*(distans**2)

    return sse

In [180]:
# X_myu_np：全データ点の座標,myu_k：全クラスタ点の座標
sse = get_sse(X_myu_np,myu_k)
print(sse)

6.926491457375577


In [ ]:
# 絶対値計算の練習
a = -3
b = 4
c = abs(a) + abs(b)
print(c)

### 【問題3】クラスタへの割り当て
全てのデータ点 Xn を最も近い中心点 μk に割り当てるコードを作成してください。

In [193]:
def cluster_allocation(q,p):
    distans = 0
    a = np.arange(9) - 4
    print(a)
    b = a.reshape((3, 3))
    print(b)
    print(LA.norm(a))
    print(LA.norm(b))    

    return distans

In [194]:
q = 1
p = 1
distans = cluster_allocation(q,p)
print(distans)

[-4 -3 -2 -1  0  1  2  3  4]
[[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]]
7.745966692414834
7.745966692414834
0
