# 解答例：Week2 授業前課題3 行列積のスクラッチ

## 行列積

以下のような行列A、Bを考えます。

$$
A = \left[
\begin{array}{ccc}
  -1 & 2 & 3 \\
  4 & -5 & 6 \\
  7 & 8 & -9
\end{array}
\right],
B = \left[
\begin{array}{ccc}
  0 & 2 & 1 \\
  0 & 2 & -8 \\
  2 & 9 & -1
\end{array}
\right]
$$

In [1]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

### 【問題1】行列積を手計算する

AとBの行列積を手計算で解いてください。

計算過程もマークダウンテキストを用いて説明してください。

（解説）

行列積の定義（計算方法）を調べ、その通りに解いてください。行列積ABとBA両方の解答を載せますが、ABのみで合格です。

計算過程にはマークダウンの数式機能を使うと綺麗なノートブックが作れます。

Jupyter NotebookではMathJaxというライブラリによってLaTeXの記法が使えます。「LaTeX　行列」のように検索してください。

$$
AB = 
\left[
\begin{array}{ccc}
  (-1)\times0+2\times0+3\times2 & (-1)\times2+2\times2+3\times9 & (-1)\times1+2\times(-8)+3\times(-1) \\
  4\times0+(-5)\times0+6\times2 & 4\times2+(-5)\times2+6\times9 & 4\times1+(-5)\times(-8)+6\times(-1) \\
  7\times0+8\times0+(-9)\times2 & -7\times0+8\times2+(-9)\times9 & 7\times1+8\times(-8)+(-9)\times(-1)
\end{array}
\right]
=\left[
\begin{array}{ccc}
  6 & 29 & -20 \\
  12 & 52 & 38 \\
  -18 & -51 & -48
\end{array}
\right]
$$

$$
BA = 
\left[
\begin{array}{ccc}
  0\times(-1)+2\times4+1\times7 & 0\times2+2\times(-5)+1\times8 & 0\times3+2\times6+1\times(-9) \\
  0\times(-1)+2\times4+(-8)\times7 & 0\times2+2\times(-5)+(-8)\times8 & 0\times3+2\times6+(-8)\times(-9) \\
  2\times(-1)+9\times4+(-1)\times7 & 2\times2+9\times(-5)+(-1)\times8 & 2\times3+9\times6+(-1)\times(-9)
\end{array}
\right]
=\left[
\begin{array}{ccc}
  15 & -2 & 3 \\
  -48 & -74 & 84 \\
  27 & -49 & 69
\end{array}
\right]
$$

### 【問題2】NumPyの関数による計算

この行列積はNumPyの`np.matmul()`や`np.dot()`、または`@`演算子を使うことで簡単に計算できます。

これらを使い行列積を計算してください。

[numpy.matmul — NumPy v1.16 Manual](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul)

[numpy.dot — NumPy v1.16 Manual](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html)

**3種類の違い**

`np.matmul()`と`np.dot()`は3次元以上の配列で挙動が変わります。`@`演算子は`np.matmul()`と同じ働きをします。

今回のような2次元配列の行列積では`np.matmul()`や`@`演算子が公式に推奨されています。以下は`np.dot()`の説明からの引用です。

> If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

（解説）

行列AとBをこの関数に入れるだけです。

`@`が登場したのが2015年9月リリースのPython3.5からなため少し古い書籍等では使われていないことも多いですが、最近ではこれが人気が高いです。

In [2]:
c_ndarray_matmul = np.matmul(a_ndarray, b_ndarray)
print("行列積AB np.matmul()の計算結果\n{}".format(c_ndarray_matmul))

c_ndarray_dot = np.dot(a_ndarray, b_ndarray)
print("行列積AB np.dot()の計算結果\n{}".format(c_ndarray_dot))

c_ndarray_at = a_ndarray@b_ndarray
print("行列積AB @の計算結果\n{}".format(c_ndarray_at))

行列積AB np.matmul()の計算結果
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
行列積AB np.dot()の計算結果
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
行列積AB @の計算結果
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [3]:
c_ndarray_at_change_order = b_ndarray@a_ndarray
print("行列積BA @の計算結果\n{}".format(c_ndarray_at_change_order))

行列積BA @の計算結果
[[ 15  -2   3]
 [-48 -74  84]
 [ 27 -49  69]]


In [4]:
%timeit c_ndarray_matmul = np.matmul(a_ndarray, b_ndarray)
%timeit c_ndarray_dot = np.dot(a_ndarray, b_ndarray)
%timeit c_ndarray_at = a_ndarray@b_ndarray

1.64 µs ± 30 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.15 µs ± 19 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.61 µs ± 19.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [5]:
# 3次元以上ではnp.matmul()とnp.dot()の挙動に違いが出る
a = np.arange(8).reshape((2, 2, 2))
b = np.arange(8).reshape((2, 2, 2))
print("-----")
print("np.matmul()\n{}".format(np.matmul(a, b)))
print("-----")
print("np.dot()\n{}".format(np.dot(a, b)))

-----
np.matmul()
[[[ 2  3]
  [ 6 11]]

 [[46 55]
  [66 79]]]
-----
np.dot()
[[[[ 2  3]
   [ 6  7]]

  [[ 6 11]
   [26 31]]]


 [[[10 19]
   [46 55]]

  [[14 27]
   [66 79]]]]


In [6]:
print("np.matmul()でshapeが異なる例の確認：{}".format(np.matmul(np.ones((2, 1, 3, 4)), np.ones((1, 5, 4, 6))).shape))
print("np.dot()でshapeが異なる例の確認：{}".format(np.dot(np.ones((2, 1, 3, 4)), np.ones((1, 5, 4, 6))).shape))

np.matmul()でshapeが異なる例の確認：(2, 5, 3, 6)
np.dot()でshapeが異なる例の確認：(2, 1, 3, 1, 5, 6)


### （発展的な話）

なぜこれを学ぶのか？というと機械学習の計算でよく使う線形写像が行列積で表現できるからです。

線形写像というと言葉が難しいですが、以下のような計算は線形写像の一種です。

$$
y = 2x
$$

xは3としましょう。この線形写像は次のような行列積に置き換えられます。

$$
y=
\left[
\begin{array}{ccc}
  2
\end{array}
\right]
\left[
\begin{array}{ccc}
  3
\end{array}
\right]
$$

NumPyで計算してみます。

In [7]:
a = np.array([[2]])
x = np.array([[3]])
y = a@x

print("a.shape : {}".format(a.shape))
print("x.shape : {}".format(x.shape))
print("-----")
print("aの中身\n{}".format(a))
print("-----")
print("xの中身\n{}".format(x))
print("---------------")
print("y.shape : {}".format(y.shape))
print("-----")
print("yの中身\n{}".format(y))

a.shape : (1, 1)
x.shape : (1, 1)
-----
aの中身
[[2]]
-----
xの中身
[[3]]
---------------
y.shape : (1, 1)
-----
yの中身
[[6]]


$$
y = 2\times3 = 6
$$

と同じ結果が得られました。

次のような計算も線形写像です。

$$
y = 2x_{1} + 5x_{2}
$$

x1は3、x2は4として計算します。次のような行列積に置き換えられます。

$$
y=
\left[
\begin{array}{ccc}
  2 & 5
\end{array}
\right]
\left[
\begin{array}{ccc}
  3 \\
  4
\end{array}
\right]
$$

In [8]:
W = np.array([[2, 5]])
X = np.array([[3], [4]])
y = W@X

print("W.shape : {}".format(W.shape))
print("X.shape : {}".format(X.shape))
print("-----")
print("Wの中身\n{}".format(W))
print("-----")
print("Xの中身\n{}".format(X))
print("---------------")
print("y.shape : {}".format(y.shape))
print("-----")
print("yの中身\n{}".format(y))

W.shape : (1, 2)
X.shape : (2, 1)
-----
Wの中身
[[2 5]]
-----
Xの中身
[[3]
 [4]]
---------------
y.shape : (1, 1)
-----
yの中身
[[26]]


$$
y = 2\times3 + 5\times4 = 26
$$

と同じ結果が得られました。

さらに、次のような計算も考えられます。このあたりから行列積に置き換えるメリットが感じられます。

$$
y_{1} = 2x_{1} + 5x_{2} \\
y_{2} = 4x_{1} + 3x_{2} \\
y_{3} = 6x_{1} + 2x_{2} \\
$$

x1は3、x2は4として計算します。次のような行列積に置き換えられます。

$$
Y=
\left[
\begin{array}{ccc}
  2 & 5 \\
  4 & 3 \\
  6 & 2
\end{array}
\right]
\left[
\begin{array}{ccc}
  3 \\
  4
\end{array}
\right]
$$

In [9]:
W = np.array([[2, 5], [4, 3], [6, 2]])
X = np.array([[3], [4]])
Y = W@X

print("W.shape : {}".format(W.shape))
print("X.shape : {}".format(X.shape))
print("-----")
print("Wの中身\n{}".format(W))
print("-----")
print("Xの中身\n{}".format(X))
print("---------------")
print("Y.shape : {}".format(Y.shape))
print("-----")
print("Yの中身\n{}".format(Y))

W.shape : (3, 2)
X.shape : (2, 1)
-----
Wの中身
[[2 5]
 [4 3]
 [6 2]]
-----
Xの中身
[[3]
 [4]]
---------------
Y.shape : (3, 1)
-----
Yの中身
[[26]
 [24]
 [26]]


3つの式が1つの行列積で表現できました。

機械学習ではこのような計算のために行列積を利用します。

## 行列積のスクラッチ実装

`np.matmul()`や`np.dot()`、または`@`演算子を使わずに、手計算で行った計算過程をNumPyによるスクラッチ実装で再現していきましょう。これにより、行列積の計算に対する理解を深めます。ここで考えるのは行列AとBのような次元が2の配列に限定します。

### 【問題3】ある要素の計算を実装

手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。

1. 行列Aの(0,0)の要素 $a_{0, 0}$ と行列Bの(0,0)の要素 $b_{0, 0}$ を掛け合わせる
2. 行列Aの(0,1)の要素 $a_{0, 1}$ と行列Bの(1,0)の要素 $a_{1, 0}$ を掛け合わせる
3. 行列Aの(0,2)の要素 $a_{0, 2}$ と行列Bの(2,0)の要素 $a_{2, 0}$ を掛け合わせる
4. それらの値を全て足し合わせる

数式で表すと

$$
\sum^{3}_{k=1}a_{0,k}b_{k,0}
$$

です。

この計算を`np.matmul()`や`np.dot()`、または`@`演算子を使わずに行うコードを書いてください。

（解説）

NumPyでまとめて計算するか、for文で要素を取り出していくかどうかです。

それぞれ時間を計測してみると、(3, 3)のshapeでは解答例2のfor文の方が速いですが、(1000, 1000)までshapeを大きくするとかなり遅いという結果になります。

（解答例1）

Aの0行目とBの0列目を取り出し、NumPyを使いまとめて掛け算した後`sum`メソッドで足し合わせます。

In [10]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

mul00 = (a_ndarray[0]*b_ndarray[:, 0]).sum()
print(" Aの0行目とBの0列目：{}".format(mul00))

 Aの0行目とBの0列目：6


（解答例2）

for文で要素を1つずつ取り出し掛け算し、それを順番に加算していきます。

In [11]:
mul00 = 0
for k in range(a_ndarray.shape[1]):
    mul00 += a_ndarray[0, k]*b_ndarray[k, 0]
print(" Aの0行目とBの0列目：{}".format(mul00))

 Aの0行目とBの0列目：6


In [12]:
%%timeit
mul00 = (a_ndarray[0]*b_ndarray[:, 0]).sum()

4.69 µs ± 82.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [13]:
%%timeit
mul00 = 0
for k in range(a_ndarray.shape[1]):
    mul00 += a_ndarray[0, k]*b_ndarray[k, 0]

2.45 µs ± 87.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [14]:
x_ndarray = np.ones((1000, 1000))
y_ndarray = np.ones((1000, 1000))

In [15]:
%%timeit
mul00 = (x_ndarray[0]*y_ndarray[:, 0]).sum()

10.3 µs ± 296 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [16]:
%%timeit
mul00 = 0
for k in range(x_ndarray.shape[1]):
    mul00 += x_ndarray[0, k]*y_ndarray[k, 0]

581 µs ± 13.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### 【問題4】行列積を行う関数の作成

問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。

行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。

計算結果である $3 \times 3$ の行列Cの各要素 $c_{i, j}$ は数式で表すと次のようになります。

$$
c_{i,j} = \sum^{3}_{k=1}a_{i,k}b_{k,j}
$$

for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。インデックス $i$ や $j$ を1増やすと、次の行や列に移ることができます。

（解説）

正しい対応で計算させられるかが重要です。紙に書くなどして、実現したい動作を確認しながらコードに落とし込みましょう。

解答例1は問題3の解答例1に対してfor文を2重に適用した方法です。ひとまずこれが書けていれば良いなという解答です。

解答例2は問題3の解答例2に対応する方法です。for文が3重になってしまうこのような処理は最終的には避けた方が良いですが、まずはこのような書き方からはじめてみても良いでしょう。

解答例3はfor文を1つも使わない方法です。ブロードキャストをうまく使うことで、for文2つ分を一気に計算させることができます。

どのような方法でも計算できていれば合格です。

（解答例1）

In [17]:
def matrix_product_q4_1(a, b):
    """
    行列積ABを計算する
    Parameters
    ----------------
    a, b : ndarray
        AとBに対応する行列
    Returns
    ----------------
    ndarray
        計算した行列積
    """
    c = np.empty((a.shape[0], b.shape[1]))

    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            c[i, j] = (a[i]*b[:, j]).sum()
    return c

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print("計算結果\n{}".format(matrix_product_q4_1(a_ndarray, b_ndarray)))

計算結果
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


（解答例2）

In [18]:
def matrix_product_q4_2(a, b):
    """
    行列積ABを計算する
    Parameters
    ----------------
    a, b : ndarray
        AとBに対応する行列
    Returns
    ----------------
    ndarray
        計算した行列積
    """
    c = np.zeros((a.shape[0], b.shape[1]))
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            for k in range(a.shape[1]):
                c[i, j] += a[i, k]*b[k, j]
    return c

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print("計算結果\n{}".format(matrix_product_q4_2(a_ndarray, b_ndarray)))

計算結果
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


（解答例3）

In [19]:
def matrix_product_q4_3(a, b):
    """
    行列積ABを計算する
    Parameters
    ----------------
    a, b : ndarray
        AとBに対応する行列
    Returns
    ----------------
    ndarray
        計算した行列積
    """
    c = (a[:, np.newaxis, :]*b.T).sum(axis=2)
    return c

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print("計算結果\n{}".format(matrix_product_q4_3(a_ndarray, b_ndarray)))

計算結果
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


解答例3を順番に可視化してみると以下のようになります。

In [20]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print("Aに軸を追加\n{}".format(a_ndarray[:, np.newaxis, :]))
print("Bを転置\n{}".format(b.T))
print("これらを掛け合わせると\n{}".format(a_ndarray.reshape(3, 1, 3)*b_ndarray.T))
print("そしてaxis=2で合計すると求めたい行列積\n{}".format((a_ndarray.reshape(3, 1, 3)*b_ndarray.T).sum(axis=2)))

Aに軸を追加
[[[-1  2  3]]

 [[ 4 -5  6]]

 [[ 7  8 -9]]]
Bを転置
[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]
これらを掛け合わせると
[[[  0   0   6]
  [ -2   4  27]
  [ -1 -16  -3]]

 [[  0   0  12]
  [  8 -10  54]
  [  4  40  -6]]

 [[  0   0 -18]
  [ 14  16 -81]
  [  7 -64   9]]]
そしてaxis=2で合計すると求めたい行列積
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


Aに軸を追加し、(3, 1, 3)としたことで、B.Tと掛け合わせる際それぞれが以下のような(3, 3, 3)の形にブロードキャストされます。

これは2重のfor文で計算させたかった9個の行や列が並んでいる状態です。やや難しいですが、NumPyを使えばこのような書き方も可能だということを意識しておきましょう。まずは単純なfor文で書いてみて、その後書き換えていくことをオススメします。

```py
# A
 [[[-1  2  3]
  [-1  2  3]
  [-1  2  3]]

 [[ 4 -5  6]
  [ 4 -5  6]
  [ 4 -5  6]]

 [[ 7  8 -9]
  [ 7  8 -91]
  [ 7  8 -9]]]
  
# B.T
 [[[ 0  0  2]
  [ 2  2  9]
  [ 1 -8 -1]]

 [[ 0  0  2]
  [ 2  2  9]
  [ 1 -8 -1]]

 [[ 0  0  2]
  [ 2  2  9]
  [ 1 -8 -1]]]
 ```

それぞれの実行時間を計測してみます。

行列の形が大きくなると解答例1や2は多重のfor文によって急激に計算時間が増えていることが分かります。

＊(10, 10)は繰り返し処理の計測に時間がかかるため、コメントアウトしています。

In [21]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

%timeit matrix_product_q4_1(a_ndarray, b_ndarray)
%timeit matrix_product_q4_2(a_ndarray, b_ndarray)
%timeit matrix_product_q4_3(a_ndarray, b_ndarray)

51.3 µs ± 1.63 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
33.4 µs ± 1.63 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
7.73 µs ± 140 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [22]:
# x_ndarray = np.ones((10, 10))
# y_ndarray = np.ones((10, 10))

# %timeit matrix_product_q4_1(x_ndarray, y_ndarray)

629 µs ± 77.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [23]:
# %timeit matrix_product_q4_2(x_ndarray, y_ndarray)

927 µs ± 30 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [24]:
# %timeit matrix_product_q4_3(x_ndarray, y_ndarray)

15.8 µs ± 166 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## 行列積が定義されない組み合わせの行列

次に以下のような例を考えます。    

$$ D = \left[
    \begin{array}{ccc}
      -1 & 2 & 3 \\
      4 & -5 & 6
    \end{array}
  \right],
  E- = \left[
    \begin{array}{ccc}
       -9 & 8 & 7 \\
      6 & -5 & 4
    \end{array}
  \right] $$

```py
d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
```

行列積DEはDの列数とEの行数が等しい場合に定義されていますから、この例では計算ができません。

### 【問題5】計算が定義されない入力を判定する

問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。

if文などによってこれを防ぎ、入力される形に問題があることを`print()`を使い表示するコードを書き加えてください。

（解説）

`a.shape[1]==b.shape[0]`の場合のみ計算を行い、そうでない場合は不適切であることを説明します。

（解答例1）

if文を使う方法です。`if a.shape[1]==b.shape[0]:`とするか`if a.shape[1]!=b.shape[0]:`とするか、どちらが読みやすいかは考え方が別れるところです。

In [25]:
def matrix_product_q5_1(a, b):
    c = np.empty((a.shape[0], b.shape[1]))

    if a.shape[1] == b.shape[0]:
        c = (a[:, np.newaxis, :]*b.T).sum(axis=2)
        return c
    else:
        print("a.shape[1] != b.shape[0] : {} != {}".format(a.shape[1], b.shape[0]))
        return None
        
d = np.array([[-1, 2, 3], [4, -5, 6]])
e = np.array([[-9, 8, 7], [6, -5, 4]])
print("計算結果\n{}".format(matrix_product_q5_1(d, e)))

a.shape[1] != b.shape[0] : 3 != 2
計算結果
None


（解答例2）

`assert`を使う方法です。指定した条件を満たさない場合はAssertionErrorでプログラムが止まります。

`assert`はデバッグのためという意味合いが出るため、今回のような例ではやや不適切かもしれません。しかし、簡単に使えるため自作の関数を作成する際に非常に便利です。手軽にテストを書くことにもなるため、積極的に使っていくことをオススメします。機械学習・データサイエンスのコードを書く場合しっかりとしたユニットテストを書くということにはならない場面も多いですが、これであれば負担なく入れることができ、後々のバグを防ぐことができます。

[7. 単純文 (simple statement) — Python 3.7.4 ドキュメント](https://docs.python.org/ja/3/reference/simple_stmts.html#assert)

In [26]:
def matrix_product_q5_2(a, b):
    c = np.empty((a.shape[0], b.shape[1]))

    assert a.shape[1] == b.shape[0], "a.shape[1] != b.shape[0] : {} != {}".format(a.shape[1], b.shape[0])
    c = (a[:, np.newaxis, :]*b.T).sum(axis=2)
    return c
        
d = np.array([[-1, 2, 3], [4, -5, 6]])
e = np.array([[-9, 8, 7], [6, -5, 4]])
print("計算結果\n{}".format(matrix_product_q5_2(d, e)))

AssertionError: a.shape[1] != b.shape[0] : 3 != 2

（解答例3）

**組み込み例外** を表示させる方法です。

組み込み例外とは、**ValueError** や **IndexError**、 **ZeroDivisionError** など、用意されているエラーの種類のことです。

ここではValueErrorを表示させることにします。次のような意味を持ちます。ざっくり値関係のエラーであればこれが使われることが多いです。

> 演算子や関数が、正しい型だが適切でない値を持つ引数を受け取ったときや、 IndexError のようなより詳細な例外では記述できない状況で送出されます。

どのエラーを選ぶこともできますが、意味が分かりやすいものにするようにしましょう。

[ValueError — Python 3.7.4 ドキュメント](https://docs.python.org/ja/3/library/exceptions.html#ValueError)

[8. エラーと例外 — Python 3.7.4 ドキュメント](https://docs.python.org/ja/3/tutorial/errors.html)

ちょっとコードを書く時には面倒なためあまり適していない方法ですが、自分以外の人も使うモジュールを作りたいという時などは良いでしょう。

In [ ]:
def matrix_product_q5_3(a, b):
    c = np.empty((a.shape[0], b.shape[1]))

    if a.shape[1] != b.shape[0]:
        raise ValueError("a.shape[1] != b.shape[0] : {} != {}".format(a.shape[1], b.shape[0]))
    c = (a[:, np.newaxis, :]*b.T).sum(axis=2)
    return c

d = np.array([[-1, 2, 3], [4, -5, 6]])
e = np.array([[-9, 8, 7], [6, -5, 4]])
print("計算結果\n{}".format(matrix_product_q5_3(d, e)))

解答例2や3の場合は、エラーが表示されプログラムが停止します。

もしも止めたくない場合には **try文による例外処理** を書くことができます。

[8.3. 例外を処理する — Python 3.7.4 ドキュメント](https://docs.python.org/ja/3/tutorial/errors.html#handling-exceptions)

以下の例では「計算できない形です。」を答えとして代入し、プログラムが続くようにしました。しかし、以下のコードはif文でも対応できるため、そういった場合はtry文よりif文の方が推奨されます。try文はif文で判断ができないどうしようもないエラーに対してのみ使う方が読みやすいコードになります。

In [ ]:
d = np.array([[-1, 2, 3], [4, -5, 6]])
e = np.array([[-9, 8, 7], [6, -5, 4]])

try:
    ans = matrix_product_q5_2(d, e)
    
except AssertionError:
    ans = "計算できない形です。"

print("計算結果\n{}".format(ans))

問題4の関数にそのまま行列を入れると、どのようなエラーになるかを確認しておきます。

In [ ]:
# エラーになる
print("計算結果\n{}".format(matrix_product_q4_1(d, e)))

In [ ]:
# エラーになる
print("計算結果\n{}".format(matrix_product_q4_2(d, e)))

In [ ]:
# エラーになる
print("計算結果\n{}".format(matrix_product_q4_3(d, e)))

### 【問題6】転置

片方の行列を転置することで、行列積が計算できるようになります。

`np.transpose()`や`.T`アトリビュートを用いて転置し、行列積を計算してください。

[numpy.transpose — NumPy v1.16 Manual](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html)

[numpy.ndarray.T — NumPy v1.16 Manual](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.T.html)

（解説）

今回の例ではどちらかを転置すれば行列積が定義された状態になるため、計算できます。

In [28]:
d = np.array([[-1, 2, 3], [4, -5, 6]])
e = np.array([[-9, 8, 7], [6, -5, 4]])

print("計算結果：\n{}".format(d.T@e))
print("計算結果：\n{}".format(d@e.T))

計算結果：
[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
計算結果：
[[ 46  -4]
 [-34  73]]
