In [2]:
import numpy as np

In [4]:
sample_ndarray = np.arange(10) #10の配列を用意する
print(sample_ndarray[3]) # 3番地の配列を出力
print(sample_ndarray[:3]) # 3番地未満の配列を出力
print(sample_ndarray[-1]) # 最後の配列を出力
print(sample_ndarray[::2]) # 2こ飛ばしで出力
print(sample_ndarray[::-1]) # 最後から順番に出力

3
[0 1 2]
9
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [10]:
# 形を変更する

In [9]:
a_ndarray = np.arange(4)
print(a_ndarray)
print(a_ndarray.shape) # 4,
b_ndarray = a_ndarray.reshape(2,2)
print(b_ndarray)
print(b_ndarray.shape)

[0 1 2 3]
(4,)
[[0 1]
 [2 3]]
(2, 2)


In [11]:
# 多次元での要素の取り出し

In [13]:
sample_ndarray = np.arange(6).reshape(2,3)
print(sample_ndarray)
sample_ndarray[1,2] # 1行2列目の要素を取り出す
sample_ndarray[:,1:] # 全ての行かつ１列めより後の列を配列として取り出す。（スライス）

[[0 1 2]
 [3 4 5]]


array([[1, 2],
       [4, 5]])

In [19]:
a_ndarray = np.arange(6) # 1行６列で定義
b_ndarray = a_ndarray.reshape(2,3) #2行3列に変更
print(a_ndarray)
print(b_ndarray)
print("shapeは{}".format(b_ndarray.shape))
print("合計値は{}".format(b_ndarray.sum()))
print("0番目の軸の方向は{}".format(b_ndarray.sum(axis=0))) #０列目を軸にしている
print("１番目の軸方向の平均は{}".format(b_ndarray.mean(axis=1))) # 1列目を軸にしている

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
shapeは(2, 3)
合計値は15
0番目の軸の方向は[3 5 7]
１番目の軸方向の平均は[1. 4.]
