In [1]:
import numpy as np

In [2]:
sample_ndarray = np.array([1,2,3])
print(sample_ndarray)

[1 2 3]


In [4]:
sample_ndarray = np.array([[1,2,3],[4,5,6]])
print(sample_ndarray)

[[1 2 3]
 [4 5 6]]


In [5]:
print(2+[1,2,3])

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [6]:
# numpy書かないで b_list に２を足す方法
a = 2
b_list = [1,2,3]
c_list = []
for b in b_list:
    c_list.append(a + b)
print(c_list)

[3, 4, 5]


In [7]:
print(2 + np.array([1,2,3]))

[3 4 5]


In [10]:
print(np.array([2,2,2]) + np.array([1,2,3]))

[3 4 5]


In [13]:
print(np.array([1,2,3]) * np.array([1,2,3]))
print(np.array([1,2,3]) > np.array([2,2,2]))

[1 4 9]
[False False  True]


In [14]:
print(np.array([2]) + np.array([1,2,3]))

[3 4 5]


In [15]:
print(np.array([2,2]) + np.array([1,2,3]))

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [21]:
# 配列情報の取得

In [22]:
print(np.array([1,2,3]).ndim)
print(np.array([1,2,3]).shape)
print(np.array([1,2,3]).dtype)

1
(3,)
int64


In [24]:
sample_ndarray = np.arange(100)
print(sample_ndarray)
print(sample_ndarray.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
(100,)


In [26]:
sample_ndarray = np.arange(50,200,2)
print(sample_ndarray)
print(sample_ndarray.shape)

[ 50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84
  86  88  90  92  94  96  98 100 102 104 106 108 110 112 114 116 118 120
 122 124 126 128 130 132 134 136 138 140 142 144 146 148 150 152 154 156
 158 160 162 164 166 168 170 172 174 176 178 180 182 184 186 188 190 192
 194 196 198]
(75,)


In [27]:
sample_ndarray = np.ones(100)
print(sample_ndarray)
print(sample_ndarray.shape)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]
(100,)


In [28]:
sample_ndarray = 7*np.ones(100)
print(sample_ndarray)
print(sample_ndarray.shape)

[7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7.
 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7.
 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7.
 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7.
 7. 7. 7. 7.]
(100,)


In [29]:
sample_ndarray = np.zeros(100)
print(sample_ndarray)
print(sample_ndarray.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
(100,)
