# Week4授業前課題3 オブジェクト指向の活用

### 【問題1】これまで利用してきたクラスの列挙

クラスを使う際はインスタンス化を行うことと、クラスの命名法がわかりました。この情報を元に、これまでの課題で利用してきたコードの中でどのようなクラスがあったかを答えてください。

Pandas、matplotlib、scikit-learnからそれぞれ1つ以上見つけてください。

クラスの例

Pandas : `pd.DataFrame`, `pd.Series`

matplotlib : `matplotlib.lines.Line2D`, `matplotlib.figure.Figure`

scikit-learn : `StandardScaler`, `KNeighborsClassifier`

### 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙
これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。


最低でもそれぞれ5つ以上答えてください。

#### Pandas : 

DataFrameクラスに対して

メソッド : `DataFrame.head`, `DataFrame.describe`, `DataFrame.sum` 
 
インスタンス変数 :  `DataFrame.columns`, `DataFrame.loc`


#### matplotlib : 

matplotlib.lines.Line2Dクラスに対して

メソッド :  `matplotlib.lines.Line2D.set_linestyle`, `matplotlib.lines.Line2D.set_marker`

インスタンス変数 :  `matplotlib.lines.Line2D. _linestyle`, `matplotlib.lines.Line2D._marker`

#### scikit-learn : 

StandardScalerクラスに対して

メソッド :  `StandardScaler.fit`, `StandardScaler.transform`

インスタンス変数 :  `StandardScaler.mean_`, `StandardScaler.var_`

KNeighborsClassifierクラスに対して

メソッド :  `KNeighborsClassifier.fit`, `KNeighborsClassifier.predict`

インスタンス変数 :  `KNeighborsClassifier.weights`, `KNeighborsClassifier.classes_`


#### 【問題3】標準化クラスをスクラッチで作成
理解をより深めるため、StandardScalerをスクラッチで作成しましょう。scikit-learnは使わず、NumPyなどを活用して標準化の計算を記述します。具体的にはfitメソッドとtransformメソッドを作ります。


今回は雛形を用意しました。クラスの作成方法は関数に近いです。メソッドはクラスの中にさらにインデントを一段下げて記述します。


インスタンス変数を作成する際はself.mean_のようにselfを付けます。クラスの外からscaler.mean_と書いていたscalerの部分が自分自身を表すselfになっています。

In [55]:
class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """

    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
#         self.sum_ = np.sum(X, axis=0)
#         self.mean_ = self.sum_ / X.shape[0]
        self.mean_ = np.mean(X, axis=0)# 平均
        self.var_ = np.var(X, axis=0)# 分散
        self.std_ = np.std(X, axis=0)# 標準偏差

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
            標準化：統計学における標準化 (standardization) とは，
            与えられたデータを平均が0で分散が1のデータに変換する操作のことをいう．
            正規化とか規格化とも呼ばれる
            平均と分散を考慮した上でのその値の凄さを評価する事が出来る！
        """
        X_scaled = (X - self.mean_)/self.std_# 標準化

        return X_scaled

In [56]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print("標準化：{}".format(X_std))

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
標準化：[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


In [57]:
# サイキットラーンで実施。手作りのデータと同じなら正解！
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(X)
x_std = ss.transform(X)
print("標準化：{}".format(x_std))

標準化：[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


In [83]:
class ExampleClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """

    def __init__(self, value):# コンストラクタはインスタンス生成の時だけ動作する
        self.value = value
        print("初期値{}が設定されました".format(self.value))
        print(type(self.value))
        assert type(self.value) in [int, float], '数値で入力してね' # falseの時に発火する。
        
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        
        assert type(value2) in [int, float], '数値で入力してね' # falseの時に発火する。

        self.value += value2

example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))


初期値5が設定されました
<class 'int'>
value : 5
value : 8


In [84]:
example = ExampleClass("5")
print("value : {}".format(example.value))

初期値5が設定されました
<class 'str'>


AssertionError: 数値で入力してね